"""
Django settings for SampleWeb project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v4u(pabkzwg)8w%zy59)y#!6+(pct1*!3!y+e$6=dix2&&vn53'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Login.apps.LoginConfig',
    'social.apps.django_app.default',
]

SITE_ID = 1
MIDDLEWARE_CLASSES = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SampleWeb.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.request',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
            ],
            'loaders':[
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]



WSGI_APPLICATION = 'SampleWeb.wsgi.application'

CORS_ORIGIN_ALLOW_ALL = True
# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        #'NAME': BASE_DIR + '/loginapp.sqlite',  # Or path to database file if using sqlite3.
        # The following settings are not used with sqlite3:
        'USER': '',
        'PASSWORD': '',
        'HOST': '',   # Empty for localhost through domain sockets or '127.0.0.1' for localhost through TCP.
        'PORT': '',   # Set to empty string for default.
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTHENTICATION_BACKENDS = [
    'social.backends.google.GoogleOAuth2',
    'social.backends.twitter.TwitterOAuth',
    'django.contrib.auth.backends.ModelBackend',
]
LOGIN_URL = '/'
LOGIN_ERROR_URL = '/login-error/'

SOCIAL_AUTH_TWITTER_KEY = 'update me'
SOCIAL_AUTH_TWITTER_SECRET = 'update me'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "925175488137-1bfjigtc6ospod6dn07qr568m85qo1s3.apps.googleusercontent.com"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "rlY6LePoZ_lI6BBwPD8NMNLV"

GOOGLE_OAUTH2_CLIENT_ID = "925175488137-1bfjigtc6ospod6dn07qr568m85qo1s3.apps.googleusercontent.com"
GOOGLE_OAUTH2_CLIENT_SECRET = "rlY6LePoZ_lI6BBwPD8NMNLV"

# SOCIAL_AUTH_COMPLETE_URL_NAME  = 'socialauth_complete'
# SOCIAL_AUTH_ASSOCIATE_URL_NAME = 'socialauth_associate_complete'
SOCIAL_AUTH_GOOGLE_CUSTOM_SCOPE = ['https://www.googleapis.com/oauth2/v1/userinfo']
ACCOUNT_USERNAME_REQUIRED = False

GOOGLE_EXTENDED_PERMISSIONS = ['email', 'user_birthday']
# CORS_ORIGIN_ALLOW_ALL = True
# SOCIAL_AUTH_LOGIN_URL = '/'
# SOCIAL_AUTH_URL_NAMESPACE = 'social'
#SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '1033619565535-gjhfe8s5c2hrhok0nqavck0ag5thh2sc.apps.googleusercontent.com'
#SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'BmtUCET7BYgNHXSFu-zSS-aC'
# SOCIAL_AUTH_ADMIN_USER_SEARCH_FIELDS = ['username', 'email']
# SOCIAL_AUTH_USER_MODEL = 'Login.models.User'

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/
#SESSION_SERIALIZER = "django.contrib.sessions.serializers.PickleSerializer"
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/log/'
SOCIAL_AUTH_LOGIN_URL = '/'
SOCIALACCOUNT_QUERY_EMAIL = True

# See: https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#staticfiles-finders
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)
